**Numerical python which is also known as numpy .it have concept called numpy array which is basically 50x faster than traditional python list. it was created in 2005 by a developer called travis oliphant , its is widely for the speed and data consistency.


In [46]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [47]:
import numpy as np

In [48]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [49]:
arr1=np.array([[1,2,3],[5,6,7]])
print(arr1)
print(arr1.ndim)

[[1 2 3]
 [5 6 7]]
2


In [50]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[20,30,40]])
print(arr2)
print(arr2.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [20 30 40]]
2


In [51]:
ar3= np.array([1,2,3,4,5,6,7,8,9,10,11])
print(ar3[0:])
print(ar3[::-3])
print(ar3[1:7:2])


[ 1  2  3  4  5  6  7  8  9 10 11]
[11  8  5  2]
[2 4 6]


In [52]:
ar3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar3)
print(ar3[1][2])
print(ar3[2][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
9


**stastical operations **

In [53]:
ar3=np.array([1,2,3,4,5,6,7,8,9])
np.max(ar3) 
np.min(ar3)
np.mean(ar3)
np.median(ar3)
np.sum(ar3)


np.int64(45)

add,multiply

In [54]:
arr1=np.array([1,2,3])
arr2=np.array([2,3,4])
np.multiply(arr1,arr2)
np.divide(arr1,arr2)
np.subtract(arr1,arr2)
np.add(arr1,arr2)


array([3, 5, 7])

**Random numbers**

In [55]:
x = np.random.rand()  #rand gives by default numbers between 0 and 1
print(x)

0.47948088260709565


In [56]:
x=np.random.rand(5)
print(x)

[0.30635191 0.647033   0.59725599 0.23762409 0.5025731 ]


In [57]:
x=np.random.randint(1,20)
print(x)

5


In [58]:
y=np.random.randint(1000,9999,size=4)
print(y)

[6636 9160 6836 4394]


In [59]:
y=np.random.randint(1000,99999,size=4)
print(y)

[86090 33229 27682  3293]


In [60]:
y=np.random.randint(100,999,size=4)
print(y)

[277 599 199 838]


In [61]:
x1=np.random.randint(100000,999999)
print(x1)

493394


**Negative numbers**

In [62]:
x1=np.random.randn()
print(x1)

0.05547472157607397


In [63]:
x1=np.random.randn(3)
print(x1)

[ 0.68163901 -0.83814903  1.49252265]


**Reshaping means changing the dimensions of array without changing its actual data**

In [64]:
a=np.array([21,23,45,56,27,99,])
new_array= a.reshape(2,3)
print(new_array)

[[21 23 45]
 [56 27 99]]


In [65]:
a=np.array([21,23,45,56,27,99,100,2,3,4])
new_array= a.reshape(2,5)
print(new_array)

[[ 21  23  45  56  27]
 [ 99 100   2   3   4]]


In [66]:
a=np.array([21,23,45,56,27,99,100,2,3])
new_array= a.reshape(3,3)
print(new_array)

[[ 21  23  45]
 [ 56  27  99]
 [100   2   3]]
