**Numerical python which is also known as numpy .it have concept called numpy array which is basically 50x faster than traditional python list. it was created in 2005 by a developer called travis oliphant , its is widely for the speed and data consistency.


In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.7 MB 552.9 kB/s eta 0:00:23
   - -------------------------------------- 0.5/12.7 MB 552.9 kB/s eta 0:00:23
   - -------------------------------------- 0.5/12.7 MB 552.9 kB/s eta 0:00:23
   -- ------------------------------------- 0.8/12.7 MB 448.4 kB/s eta 0:00:27
   -- ------------------------------------- 0.8/12.7 MB 448.4 kB/s eta 0:00:27
   -- ------------------------------------- 0.8/12.7 MB 448.4 kB/s eta 0:00:27
   -- ------------------------------------- 0.8/12.7 MB 448.4 kB/s eta 0:00:27
   -- ---------------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [5]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [9]:
arr1=np.array([[1,2,3],[5,6,7]])
print(arr1)
print(arr1.ndim)

[[1 2 3]
 [5 6 7]]
2


In [4]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[20,30,40]])
print(arr2)
print(arr2.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [20 30 40]]
2
