**Numerical python which is also known as numpy .it have concept called numpy array which is basically 50x faster than traditional python list. it was created in 2005 by a developer called travis oliphant , its is widely for the speed and data consistency.


In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [4]:
arr1=np.array([[1,2,3],[5,6,7]])
print(arr1)
print(arr1.ndim)

[[1 2 3]
 [5 6 7]]
2


In [5]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[20,30,40]])
print(arr2)
print(arr2.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [20 30 40]]
2


In [6]:
ar3= np.array([1,2,3,4,5,6,7,8,9,10,11])
print(ar3[0:])
print(ar3[::-3])
print(ar3[1:7:2])


[ 1  2  3  4  5  6  7  8  9 10 11]
[11  8  5  2]
[2 4 6]


In [4]:
ar3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar3)
print(ar3[1][2])
print(ar3[2][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
9


**stastical operations **

In [ ]:
ar3=np.array([1,2,3,4,5,6,7,8,9])
np.max(ar3) 
np.min(ar3)
np.mean(ar3)
np.median(ar3)
np.sum(ar3)


np.int64(45)

add,multiply

In [9]:
arr1=np.array([1,2,3])
arr2=np.array([2,3,4])
np.multiply(arr1,arr2)
np.divide(arr1,arr2)
np.subtract(arr1,arr2)
np.add(arr1,arr2)
print(arr1)

[1 2 3]


In [5]:
ar3=np.array([1,2,3,4,5,6,7,8,9])
np.max(ar3) 
np.min(ar3)
np.mean(ar3)
np.median(ar3)
np.sum(ar3)


np.int64(45)