**Numerical python which is also known as numpy .it have concept called numpy array which is basically 50x faster than traditional python list. it was created in 2005 by a developer called travis oliphant , its is widely for the speed and data consistency.


In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [4]:
arr1=np.array([[1,2,3],[5,6,7]])
print(arr1)
print(arr1.ndim)

[[1 2 3]
 [5 6 7]]
2


In [5]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[20,30,40]])
print(arr2)
print(arr2.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [20 30 40]]
2


In [6]:
ar3= np.array([1,2,3,4,5,6,7,8,9,10,11])
print(ar3[0:])
print(ar3[::-3])
print(ar3[1:7:2])


[ 1  2  3  4  5  6  7  8  9 10 11]
[11  8  5  2]
[2 4 6]


In [7]:
ar3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar3)
print(ar3[1][2])
print(ar3[2][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
9


**stastical operations **

In [8]:
ar3=np.array([1,2,3,4,5,6,7,8,9])
np.max(ar3) 
np.min(ar3)
np.mean(ar3)
np.median(ar3)
np.sum(ar3)


np.int64(45)

add,multiply

In [9]:
arr1=np.array([1,2,3])
arr2=np.array([2,3,4])
np.multiply(arr1,arr2)
np.divide(arr1,arr2)
np.subtract(arr1,arr2)
np.add(arr1,arr2)


array([3, 5, 7])

**Random numbers**

In [10]:
x = np.random.rand()  #rand gives by default numbers between 0 and 1
print(x)

0.7645637678616065


In [11]:
x=np.random.rand(5)
print(x)

[0.05941609 0.69634147 0.70293471 0.72218407 0.28791265]


In [12]:
x=np.random.randint(1,20)
print(x)

11


In [13]:
y=np.random.randint(1000,9999,size=4)
print(y)

[4494 9899 5355 6715]


In [14]:
y=np.random.randint(1000,99999,size=4)
print(y)

[25597 53065 78983 83896]


In [15]:
y=np.random.randint(100,999,size=4)
print(y)

[346 947 387 828]


In [16]:
x1=np.random.randint(100000,999999)
print(x1)

310861


**Negative numbers**

In [17]:
x1=np.random.randn()
print(x1)

1.7581941848780736


In [18]:
x1=np.random.randn(3)
print(x1)

[-0.38019902  1.45403493  1.25942644]


**Reshaping means changing the dimensions of array without changing its actual data**

In [19]:
a=np.array([21,23,45,56,27,99,])
new_array= a.reshape(2,3)
print(new_array)

[[21 23 45]
 [56 27 99]]


In [20]:
a=np.array([21,23,45,56,27,99,100,2,3,4])
new_array= a.reshape(2,5)
print(new_array)

[[ 21  23  45  56  27]
 [ 99 100   2   3   4]]


In [21]:
a=np.array([21,23,45,56,27,99,100,2,3])
new_array= a.reshape(3,3)
print(new_array)

[[ 21  23  45]
 [ 56  27  99]
 [100   2   3]]


In [22]:
a1= np.array([2,4,6,8])


In [23]:
np.power(a1,2)


array([ 4, 16, 36, 64])

In [24]:
np.sqrt(a1)

array([1.41421356, 2.        , 2.44948974, 2.82842712])